.import _jmp_bank
.import autofire_lda_dc00
.import autofire_lda_dc01
.import autofire_ldx_dc00
.import autofire_ldx_dc01
.import autofire_ldy_dc00
.import autofire_ldy_dc01
.import _jmp_bank,_enable_fcbank0,_disable_fc3rom_set_01
.import _load_ptr2_rom_hidden
.import _swap_ptr2_ptr3_rom_hidden
.import ultimax_draw_menu
.import ultimax_highlight_selected_menu
.import _freezer_upd_sprptr_16k
.import _show_view_menu
.import _freezer_run
.import _freezer_pset
.import lda_txtptr_indy
.import skip_ext
.import out_inc_txtptr
.import inc_txtptr
